steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME",
        "--build-arg",
        "VERSION=$TAG_NAME",
        "--build-arg",
        "COMMIT=$COMMIT_SHA",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
